name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Type check
      run: pnpm typecheck

    - name: Lint
      run: pnpm lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build apps
      run: pnpm build

    - name: Deploy to Fly.io
      run: |
        fly deploy --remote-only
      working-directory: ./apps/api

    - name: Deploy Worker to Fly.io
      run: |
        fly deploy --remote-only
      working-directory: ./apps/worker

    - name: Deploy Admin to Fly.io
      run: |
        fly deploy --remote-only
      working-directory: ./apps/admin